Repository aukletio/Auklet-Agent-Django, pull requests merged in 2018-10, with the labels that each got.

#4 Remove Duplicate README
  README.md
Labels: bug

#6 Remove PR validation logic
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/post-release.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
Labels: devops

#7 Add requirements.txt
  requirements.txt
Labels: bug

#8 DevOps tasks for first release
  .devops/deploy.sh
  LICENSE
  MANIFEST.in
  README.md
  README.rst
  advanced_setup.rst
  setup.cfg
  setup.py
Labels: devops

#10 Add missing PEP-440 version logic
  .circleci/config.yml
  .devops/semverTo440.js
  .devops/semverTo440.sh
Labels: devops

#9 Release Candidate Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/deploy.sh
  .devops/post-release.sh
  .devops/semverTo440.js
  .devops/semverTo440.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  LICENSE
  MANIFEST.in
  README.md
  README.rst
  advanced_setup.rst
  requirements.txt
  setup.cfg
  setup.py
Labels: release

#3 Initial Production Release
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/deploy.sh
  .devops/post-release.sh
  .devops/semverTo440.js
  .devops/semverTo440.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .gitignore
  LICENSE
  MANIFEST.in
  README.md
  auklet/__about__.py
  auklet/__init__.py
  auklet/apps.py
  auklet/broker.py
  auklet/client.py
  auklet/errors.py
  auklet/middleware.py
  auklet/monitoring/__init__.py
  auklet/monitoring/logging.py
  auklet/stats.py
  auklet/utils.py
  requirements.txt
  setup.cfg
  setup.py
Labels: release

#11 Fix CircleCI image
  .circleci/config.yml
Labels: bug

#12 Release Candidate Review
  .circleci/config.yml
Labels: release

#13 Redo Initial Production Release
  .circleci/config.yml
Labels: release

#14 Utilize runtime user's root or tmp for certs
  auklet/broker.py
  auklet/client.py
  auklet/utils.py
Labels: bug

#15 Release Candidate Review
  auklet/broker.py
  auklet/client.py
  auklet/utils.py
Labels: release

#16 Release Review
  auklet/broker.py
  auklet/client.py
  auklet/utils.py
Labels: release

#17 Fix typo
  auklet/utils.py
Labels: bug

#22 Release Candidate Review
  auklet/utils.py
Labels: release

#23 Release Review
  auklet/utils.py
Labels: release

#25 Release Candidate Review
  auklet/utils.py
Labels: release

#26 Release Review
  auklet/utils.py
Labels: release

#27 Fixing a few more directory and string items
  auklet/utils.py
Labels: bug

#28 Release Candidate Review
  auklet/utils.py
Labels: release

#29 Release Review
  auklet/utils.py
Labels: release

#30 Fixing default produce call
  auklet/broker.py
Labels: bug

#31 Release Candidate Review
  auklet/broker.py
Labels: release

#32 Release Review
  auklet/broker.py
Labels: release

#33 Fixing response logic
  auklet/broker.py
Labels: bug

#34 Release Candidate Review
  auklet/broker.py
Labels: release

#35 Release Review
  auklet/broker.py
Labels: release

#37 Release Candidate Review
  auklet/broker.py
Labels: release

#38 Release Review
  auklet/broker.py
Labels: release

#39 Add release instructions to readme
  README.md
  auklet/broker.py
Labels: bug

#40 Release Candidate Review
  README.md
  auklet/broker.py
Labels: release

#41 Release Review
  README.md
  auklet/broker.py
Labels: release

#43 Release Candidate Review
  README.md
  auklet/middleware.py
Labels: release

#44 Release Review
  README.md
  auklet/middleware.py
Labels: release

#45 QoS Removal & Preemptive Certs
  auklet/broker.py
  auklet/client.py
Labels: bug

#46 Release Candidate Review
  auklet/broker.py
  auklet/client.py
Labels: release

#47 Release Review
  auklet/broker.py
  auklet/client.py
Labels: release

#48 Add duplicate build check
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
Labels: devops

#49 Fix duplicate build check
  .devops/duplicateBuildCheck.sh
Labels: devops

#50 Fix duplicate build check again
  .devops/duplicateBuildCheck.sh
Labels: devops

#52 Fix duplicate build check exit logic yet again
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
Labels: devops

#53 Release Candidate Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
Labels: release

#54 Release Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
Labels: release

#59 Readme improvements
  README.md
Labels: enhancement

#60 Release Candidate Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  README.md
Labels: release

#61 Release Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  README.md
Labels: release

#58 Performance Monitoring
  auklet/client.py
  auklet/middleware.py
  auklet/monitoring/__init__.py
  auklet/stats.py
  auklet/utils.py
Labels: enhancement
