Repository aukletio/Auklet-Agent-Django, pull requests merged in 2018-11, with the labels that each got.

#63 Pass Correct Context to MQTT Constructor
  auklet/broker.py
Labels: bug

#62 Release Candidate Review
  auklet/broker.py
  auklet/client.py
  auklet/middleware.py
  auklet/monitoring/__init__.py
  auklet/stats.py
  auklet/utils.py
Labels: release

#64 Release Review
  auklet/broker.py
  auklet/client.py
  auklet/middleware.py
  auklet/monitoring/__init__.py
  auklet/stats.py
  auklet/utils.py
Labels: release

#65 Update instructions for bug reports
  README.md
Labels: devops

#66 Fixing Code Climate links
  README.md
Labels: enhancement

#67 Release Candidate Review
  README.md
Labels: release

#68 Release Review
  README.md
Labels: release

#69 APM-1690: Deploy all branches to PyPI
  .devops/deploy.sh
Labels: enhancement
